### ISSUE TITLE
Missing 'Theme' export in NPM install option

### ISSUE THREAD

**Issue by corepay** [ArthurClemens/primer_live#125]
Hi, love this css thank you for the port.

Implementing in a fresh 17.7 project looks like the 'Theme' function is missing.

<img width="833" alt="image" src="https://github.com/ArthurClemens/primer_live/assets/48992923/f81778fd-0c6b-433e-b221-9246ee432e9c">

`app.js`
<img width="485" alt="image" src="https://github.com/ArthurClemens/primer_live/assets/48992923/ea44e02c-4918-46a4-b02f-4daa87cc718a">

`console`
<img width="763" alt="image" src="https://github.com/ArthurClemens/primer_live/assets/48992923/c9936112-228c-4e48-a4bb-db17c5ee1cb8">

`../deps/primer_live/priv/static/primer-live.esm.js`
<img width="438" alt="image" src="https://github.com/ArthurClemens/primer_live/assets/48992923/87c3a3e5-ca4a-489e-b71c-6a6638b514f2">

**Comment by ArthurClemens** [comment]
The `Theme` hook is removed in `0.4.0` because that solution did not work for persisting the selected theme. Unfortunately I did not update all of the documentation.

`theme/theme.ex` includes the deprecation note:

### Session for theme state has been removed

Using the session to store the theme state (for example [using a AJAX call roundtrip](https://thepugautomatic.com/2020/05/persistent-session-data-in-phoenix-liveview/)) does not work as expected: when navigating to another LiveView page, the updated session data is not refetched and only becomes available after a page refresh. This means that the previous offered solution with `PrimerLive.ThemeSessionController` is no longer recommended and in fact removed.

## Alternatives: database or cache

If you already have a database set up for storing data by session ID, it's a small step to integrate the theme state with it.

- [Database Session Store with Elixir and Plug (2021)](https://kimlindholm.medium.com/database-session-store-with-elixir-and-plug-4354740e2f58)

On the other hand, for a lightweight solution you may find caching simpler to start with. For example [Cachex](https://github.com/whitfin/cachex) (which I've selected for [primer-live.org](https://primer-live.org)).

- [Cachex with Phoenix (2020)](https://www.alenm.com/code/phoenix-cachex)
- [Use caching to speed up data loading in Phoenix LiveView](https://fullstackphoenix.com/quick_tips/liveview-caching)

## Handling user selection

Assuming you are providing a [theme menu](`PrimerLive.Component.theme_menu_options/1`) on the website, the option the user selects must be stored in persistent storage.

Here we're setting event callback "store_theme" in the theme menu:

```
# Some app component

<.action_menu>
  <:toggle class="btn btn-invisible">
    <.octicon name="sun-16" />
  </:toggle>
  <.theme_menu_options
    theme_state={@theme_state}
    update_theme_event="store_theme"
  />
</.action_menu>
```

The callback is invoked whenever a theme menu option is clicked. See attr [`update_theme_event`](`PrimerLive.Component.theme_menu_options/1`) for documentation of the arguments.

```
# App LiveView

def handle_event(
  "store_theme",
  %{"data" => data, "key" => key, "value" => _},
  socket
) do
  # Persist new theme state ...

  {:noreply, socket}
end
```
