### ISSUE TITLE
Advise on learning and using PrimerLive

### ISSUE THREAD

**Issue by CharlesIrvineKC** [ArthurClemens/primer_live#178]
Hello Arthur,

I've chose PrimerLive for my Phoenix/LiveView project. Just a quick couple of questions:

1. You may think this an odd question, do you have any caution regarding my use of PrimerLive?
2. Do you have any advice, in general, on how to learn and use PrimerLive?
3. I see that it is based on GitHub's Primer Design System. Do I need to read the documentation for that?
4. At the Primer Design website, I see mention of Figma. Should I try to learn that?

**Comment by ArthurClemens** [comment]
When I started PrimerLive 2 years ago, I selected GitHub Primer because of its simplicity, focus on accessibility and completeness of documentation. The components were HTML-first and easy to enhance with CSS classes.
Soon after, things changed on the website: HTML-first got replaced by React and Rails, components got added with specs only, no code, and the Primer CSS repo got frozen.
Compare with [the original website](https://thedude53.github.io/primer-css-GatsbyDocs/css/).

Implementing new components is harder, because there's no plain CSS file to base the code upon.

Regarding your first question: In its current state, PrimerLive is quite complete, but when GitHub implements new components I am unsure if the available code can be used to implement them in PrimerLive. 

Learning a component library is best done doing. Take a component, pull up the documentation for that component, and see examples of use in the storybook app.

I think the original website (linked above) gives a better view of the documentation. Use it when you need styling that is not available out of the box.

Figma is useful if you want to create mockups or wireframes. Most of the time it is easier to just use a component.

**Comment by CharlesIrvineKC** [comment]
Thanks

**Comment by mperrotti** [comment]
@ArthurClemens - this is so cool! I'm one of the maintainers of Primer and came stumbled this project. I wanted to pop in to respond to something from your comment:

> ...components got added with specs only, no code, and the Primer CSS repo got frozen.

The Primer docs now have code examples in React. Still no CSS though. If you're curious to see code examples of our Rails implementation, you can check out the [Lookbook](https://primer.style/view-components/lookbook/) for [primer/view_components](https://github.com/primer/view_components)
