### ISSUE TITLE
Support other phx- attribute

### ISSUE THREAD

**Issue by yujonglee** [ArthurClemens/primer_live#202]
https://github.com/ArthurClemens/primer_live/blob/0526e29456cda146f1f9adcc6505d6ffe428b3cf/lib/helpers/declaration_helpers.ex#L38-L42

I need `phx-target` and `phx-value-*`, but it cause `undefined attribute "phx-target" in slot "item" for component...`.

Not sure it is possible to extend from user-side.

**Comment by yujonglee** [comment]
For ex,

```elixir
<Primer.tabnav aria_label="Tabs">
  <:item
    is_selected={Enum.at(@tabs, 0) == @tab}
    phx-click="set-tab"
    phx-target={@myself}
    phx-value-tab={Enum.at(@tabs, 0)}
  >
    <%= Enum.at(@tabs, 0) %>
  </:item>
  <:item
    is_selected={Enum.at(@tabs, 1) == @tab}
    phx-click="set-tab"
    phx-target={@myself}
    phx-value-tab={Enum.at(@tabs, 1)}
  >
    <%= Enum.at(@tabs, 1) %>
  </:item>
</Primer.tabnav>
```

**Comment by ArthurClemens** [comment]
These are warnings, not errors. It is mainly annoying because it clutters the terminal log with warnings, but functionally it should just work (as you should be able to verify viewing the generated HTML).

Attributes "phx-click" and "phx-target" should be added from documentation point of view. However, Phoenix slots do not accept wildcard attributes, so "phx-value-*" can't be used for parameter "phx-value-something".
And this is a pity, because the slot model is a perfect fit for repeated elements such as tabs or list items.

**Comment by ArthurClemens** [comment]
@yujonglee Let me know if you have any problems getting the tab functionality working.

**Comment by yujonglee** [comment]
@ArthurClemens thank you for detailed explanation. I got it working, but I had to turn off `mix compile --warning-as-error` in my CI. 😢

**Comment by ArthurClemens** [comment]
Great. 

In the next release, the `item` slots will allow these attributes:
- `phx-click`
- `phx-target`
- `phx-value-item`

Then you can write:
```
<:item
  :for={%{label: label, id: tab_id} <- @tabs}
  is_selected={id == @selected_tab}
  phx-click="set_tab"
  phx-value-item={tab_id}
>     
  ...

def handle_event(
  "set_tab", %{"item" => tab_id}, socket) do
  ...
```

When using these predefined attributes, no warnings should appear.

**Comment by yujonglee** [comment]
@ArthurClemens 

great! looking forward to the next release!

**Comment by yujonglee** [comment]
@ArthurClemens Has `phx-value-item` been implemented in the `development` branch?

**Comment by ArthurClemens** [comment]
I've merged right now.
